services:
  - type: web
    name: noww-club-ai-testing
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --logger.level=info
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RENDER
        value: "true"
      - key: PYTHON_ENV
        value: "production"
      - key: LOG_LEVEL
        value: "INFO"
