services:
  - type: web
    name: noww-club-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
